name: Continuous Integration

on:
  push:
    branches:
      - develop
   

jobs:
  my-app-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1

      - name: Install dependencies
        run: npm ci
        working-directory: ./my-app
      
    

      - name: Run Cypress tests
        run: npx start-server-and-test "npm run dev" http://localhost:3000 "npm run cypress:headless"
        working-directory: ./my-app

   