name: Worflow 

on:
  push:
    branches:
      - main
    paths:
      - 'my-app/**.js'
      - 'my-app/**.json'
      - 'my-app/**.yml'

jobs:
  my-app-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1

      - name: Install dependencies
        run: npm install
        working-directory: ./my-app

      - name: Run Cypress tests
        run: npm run cypress:headless
        working-directory: ./my-app